In [2]:
## importing libraries
import pandas as pd
import sqlite3

workflow:
1. you need to establish a connection to a sqlite database by creating connection using .connect(db)
2.then, you have to create a cursor using the cursor() method
3. then, ececute the query -> cursor_object.execute('')
4.to featch the data or output, then use fetchall() method from cursor object

In [3]:
conn = sqlite3.connect('movies.sqlite')

In [4]:
cur = conn.cursor()

In [5]:
cur.execute('select name from sqlite_master where type="table"')

In [6]:
cur.fetchall()

[('movies',), ('sqlite_sequence',), ('directors',)]

In [7]:
x = cur.execute('select * from movies')

In [8]:
x.description

(('id', None, None, None, None, None, None),
 ('original_title', None, None, None, None, None, None),
 ('budget', None, None, None, None, None, None),
 ('popularity', None, None, None, None, None, None),
 ('release_date', None, None, None, None, None, None),
 ('revenue', None, None, None, None, None, None),
 ('title', None, None, None, None, None, None),
 ('vote_average', None, None, None, None, None, None),
 ('vote_count', None, None, None, None, None, None),
 ('overview', None, None, None, None, None, None),
 ('tagline', None, None, None, None, None, None),
 ('uid', None, None, None, None, None, None),
 ('director_id', None, None, None, None, None, None))

In [9]:
names = [i[0] for i in x.description]

In [10]:
names

['id',
 'original_title',
 'budget',
 'popularity',
 'release_date',
 'revenue',
 'title',
 'vote_average',
 'vote_count',
 'overview',
 'tagline',
 'uid',
 'director_id']

In [11]:
cur.execute('select * from movies')

In [12]:
movies = cur.fetchall()

In [13]:
movies = pd.DataFrame(movies,columns=names)

In [14]:
movies

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
0,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762
1,43598,Pirates of the Caribbean: At World's End,300000000,139,2007-05-19,961000000,Pirates of the Caribbean: At World's End,6.9,4500,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",285,4763
2,43599,Spectre,245000000,107,2015-10-26,880674609,Spectre,6.3,4466,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,206647,4764
3,43600,The Dark Knight Rises,250000000,112,2012-07-16,1084939099,The Dark Knight Rises,7.6,9106,Following the death of District Attorney Harve...,The Legend Ends,49026,4765
4,43601,John Carter,260000000,43,2012-03-07,284139100,John Carter,6.1,2124,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",49529,4766
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4768,48395,El Mariachi,220000,14,1992-09-04,2040920,El Mariachi,6.6,238,El Mariachi just wants to play his guitar and ...,"He didn't come looking for trouble, but troubl...",9367,5097
4769,48396,Newlyweds,9000,0,2011-12-26,0,Newlyweds,5.9,5,A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...,72766,6485
4770,48397,"Signed, Sealed, Delivered",0,1,2013-10-13,0,"Signed, Sealed, Delivered",7.0,6,"""Signed, Sealed, Delivered"" introduces a dedic...",None,231617,7108
4771,48398,Shanghai Calling,0,0,2012-05-03,0,Shanghai Calling,5.7,7,When ambitious New York attorney Sam is sent t...,A New Yorker in Shanghai,126186,7109
4772,48399,My Date with Drew,0,1,2005-08-05,0,My Date with Drew,6.3,16,Ever since the second grade when he first saw ...,None,25975,7110

In [15]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4773 entries, 0 to 4772
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              4773 non-null   int64
 1   original_title  4773 non-null   object
 2   budget          4773 non-null   int64
 3   popularity      4773 non-null   int64
 4   release_date    4773 non-null   object
 5   revenue         4773 non-null   int64
 6   title           4773 non-null   object
 7   vote_average    4773 non-null   float64
 8   vote_count      4773 non-null   int64
 9   overview        4770 non-null   object
 10  tagline         3951 non-null   object
 11  uid             4773 non-null   int64
 12  director_id     4773 non-null   int64
dtypes: float64(1), int64(7), object(5)
memory usage: 484.9+ KB

In [16]:
movies.describe()

,id,budget,popularity,revenue,vote_average,vote_count,uid,director_id
count,4773.000000,4.773000e+03,4773.000000,4.773000e+03,4773.000000,4773.000000,4773.000000,4773.000000
mean,45985.680913,2.922461e+07,21.136602,8.277710e+07,6.109177,694.541588,56244.396396,5586.661429
std,1382.032760,4.078679e+07,31.864132,1.632374e+08,1.146789,1237.251355,87452.149183,670.413263
min,43597.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,5.000000,4762.000000
25%,44790.000000,9.500000e+05,4.000000,0.000000e+00,5.600000,55.000000,8998.000000,5011.000000
50%,45983.000000,1.500000e+07,13.000000,1.947811e+07,6.200000,238.000000,14517.000000,5389.000000
75%,47176.000000,4.000000e+07,28.000000,9.361701e+07,6.800000,742.000000,57876.000000,6086.000000
max,48399.000000,3.800000e+08,875.000000,2.787965e+09,10.000000,13752.000000,459488.000000,7110.000000

In [17]:
x = cur.execute('select * from directors')

In [18]:
names = [i[0] for i in x.description]

In [19]:
names

['name', 'id', 'gender', 'uid', 'department']

In [20]:
cur.execute('select * from directors')

In [21]:
directors = cur.fetchall()

In [22]:
directors = pd.DataFrame(directors,columns=names)

In [23]:
directors

                   name    id  gender      uid department
0         James Cameron  4762       2     2710  Directing
1        Gore Verbinski  4763       2     1704  Directing
2            Sam Mendes  4764       2       39  Directing
3     Christopher Nolan  4765       2      525  Directing
4        Andrew Stanton  4766       2        7  Directing
...                 ...   ...     ...      ...        ...
2344      Shane Carruth  7106       2    76624  Directing
2345   Neill Dela Llana  7107       0  1174437  Directing
2346        Scott Smith  7108       0  1219158  Directing
2347        Daniel Hsia  7109       2   208138  Directing
2348   Brian Herzlinger  7110       2    85563  Directing

[2349 rows x 5 columns]

In [24]:
####### check how many movies are present in imdb dataset
cur.execute('select count(id) from movies')
cur.fetchall()

[(4773,)]

In [25]:
#####find the data of these three directors : James Cameron,Luc Besson. John Woo
cur.execute('select * from directors where name in ("James Cameron","Luc Besson","John Woo")')
cur.fetchall()

[('James Cameron', 4762, 2, 2710, 'Directing'),
 ('John Woo', 4893, 2, 11401, 'Directing'),
 ('Luc Besson', 4949, 2, 59, 'Directing')]

In [26]:
cur.execute('select name from directors where name like "steven%"')
cur.fetchall()

[('Steven Spielberg',),
 ('Steven Soderbergh',),
 ('Steven Brill',),
 ('Steven Zaillian',),
 ('Steven Quale',),
 ('Steven Seagal',),
 ('Steven E. de Souza',),
 ('Steven Shainberg',),
 ('Steven R. Monroe',)]

In [27]:
cur.execute('select name from directors where gender=1')
cur.fetchall()

[('Brenda Chapman',),
 ('Lilly Wachowski',),
 ('Jennifer Yuh Nelson',),
 ('Kathryn Bigelow',),
 ('Nancy Meyers',),
 ('Jill Culton',),
 ('Mimi Leder',),
 ('Vicky Jenson',),
 ('Betty Thomas',),
 ('Angelina Jolie',),
 ('Karyn Kusama',),
 ('Phyllida Lloyd',),
 ('Angela Robinson',),
 ('Beeban Kidron',),
 ('Deepa Mehta',),
 ('Penny Marshall',),
 ('Julie Taymor',),
 ('Susan Stroman',),
 ('Catherine Hardwicke',),
 ('Julie Anne Robinson',),
 ('Anne Fletcher',),
 ('Sam Taylor-Johnson',),
 ('Joan Chen',),
 ('Diane Keaton',),
 ('Sofia Coppola',),
 ('Elaine May',),
 ('Dennie Gordon',),
 ('Jennifer Flackett',),
 ('Nanette Burstein',),
 ('Liz Friedlander',),
 ('Martha Coolidge',),
 ('Niki Caro',),
 ('Liliana Cavani',),
 ('Elizabeth Banks',),
 ('Callie Khouri',),
 ('Sanaa Hamri',),
 ('Jodie Foster',),
 ('Sharon Maguire',),
 ('Cathy Malkasian',),
 ('Kirsten Sheridan',),
 ('Rachel Talalay',),
 ('Inna Evlannikova',),
 ('Bonnie Hunt',),
 ('Mary McGuckian',),
 ('Anne Fontaine',),
 ('Mira Nair',),
 ('Jessie Nelson',),
 ('Deborah Kaplan',),
 ('Katt Shea',),
 ('Thea Sharrock',),
 ('Ava DuVernay',),
 ('Jun Falkenstein',),
 ('Jessica Bendinger',),
 ('Amy Heckerling',),
 ('Nancy Walker',),
 ('Audrey Wells',),
 ('Kasi Lemmons',),
 ('Andrea Di Stefano',),
 ('Diane English',),
 ('Clare Kilner',),
 ('Susanne Bier',),
 ('Gillian Armstrong',),
 ('Sara Sugarman',),
 ('Gina Prince-Bythewood',),
 ('Elizabeth Allen Rosenbaum',),
 ('Lone Scherfig',),
 ('Drew Barrymore',),
 ('Mary Lambert',),
 ('Katja von Garnier',),
 ('Bronwen Hughes',),
 ('Daisy von Scherler Mayer',),
 ('Isabel Coixet',),
 ('Tamra Davis',),
 ('Darnell Martin',),
 ('Jane Campion',),
 ('Antonia Bird',),
 ('Agnieszka Holland',),
 ('Lisa Azuelos',),
 ('Léa Pool',),
 ('Patricia Rozema',),
 ('Lorene Scafaria',),
 ('Katherine Dieckmann',),
 ('Kari Skogland',),
 ('Gurinder Chadha',),
 ('Emily Young',),
 ('Maïwenn',),
 ('Mary Harron',),
 ('Nicole Holofcener',),
 ('Fina Torres',),
 ('Coky Giedroyc',),
 ('Claudia Llosa',),
 ('Sharron Miller',),
 ('Lynne Ramsay',),
 ('Shari Springer Berman',),
 ('Rachel Perkins',),
 ('Caroline Link',),
 ('Risa Bramon Garcia',),
 ('Deb Hagan',),
 ('Joey Lauren Adams',),
 ('Liv Ullmann',),
 ('Patty Jenkins',),
 ('Christine Jeffs',),
 ('Marcia Bennett',),
 ('Gabriela Tagliavini',),
 ('Agnieszka Wojtowicz-Vosloo',),
 ('Lisa Cholodenko',),
 ('Allison Anders',),
 ('Ruba Nadda',),
 ('Amanda Gusack',),
 ('Karen Moncrieff',),
 ('Nnegest Likké',),
 ('Jill Sprecher',),
 ('Andrea Arnold',),
 ('Francesca Gregorini',),
 ('Alison Maclean',),
 ('Alice Wu',),
 ('Hayley Cloake',),
 ('Debra Granik',),
 ('Miranda July',),
 ('Marielle Heller',),
 ('Kelly Reichardt',),
 ('Jehane Noujaim',),
 ('Vera Farmiga',),
 ('Sally Potter',),
 ('Nadine Labaki',),
 ('Adrienne Shelly',),
 ('Rebecca Miller',),
 ('Tara Subkoff',),
 ('Jamie Babbit',),
 ('Anna Muylaert',),
 ('Mona Lerche',),
 ('Gillian Robespierre',),
 ('Courtney Hunt',),
 ('Katherine Brooks',),
 ('Mary Pat Kelly',),
 ('Lori Petty',),
 ('Katie Aselton',),
 ('Allison Burnett',),
 ('Maryam Keshavarz',),
 ('Catherine Jelski',),
 ('Amy Holden Jones',),
 ('Marilyn Agrelo',),
 ('Neema Barnette',),
 ('Maria Maggenti',),
 ('Hilary Brougher',),
 ('Marianna Palka',),
 ('Ricki Stern',),
 ('Lynn Shelton',),
 ('Julie Davis',),
 ('Lena Dunham',)]

In [28]:
cur.execute('select count(gender) from directors where gender=1')
cur.fetchall()

[(150,)]

In [29]:
cur.execute('SELECT * FROM directors WHERE gender = 1 LIMIT 10')
y=cur.fetchall()
y[-1]

('Angelina Jolie', 5086, 1, 11701, 'Directing')

In [30]:
cur.execute('SELECT * FROM directors WHERE gender = 1 LIMIT 9,1')
cur.fetchall()

[('Angelina Jolie', 5086, 1, 11701, 'Directing')]

In [31]:
cur.execute('SELECT * FROM directors WHERE gender = 1 LIMIT 1 offset 9')
cur.fetchall()

[('Angelina Jolie', 5086, 1, 11701, 'Directing')]

In [32]:
movies.columns

Index(['id', 'original_title', 'budget', 'popularity', 'release_date',
       'revenue', 'title', 'vote_average', 'vote_count', 'overview', 'tagline',
       'uid', 'director_id'],
      dtype='object')

In [33]:
cur.execute('SELECT title,popularity FROM movies ORDER BY popularity desc LIMIT 3')
cur.fetchall()

[('Minions', 875), ('Interstellar', 724), ('Deadpool', 514)]

In [34]:
cur.execute('SELECT original_title FROM movies where release_date>"2000-01-01" ORDER BY vote_average desc limit 2')
cur.fetchall()

[('Sardaarji',), ('千と千尋の神隠し',)]

In [35]:
cur.execute('SELECT original_title FROM movies inner join directors on movies.director_id=directors.id where directors.name="brenda champan"')
cur.fetchall()

[]

In [36]:
cur.execute('select name from directors')
cur.fetchall()

[('James Cameron',),
 ('Gore Verbinski',),
 ('Sam Mendes',),
 ('Christopher Nolan',),
 ('Andrew Stanton',),
 ('Sam Raimi',),
 ('Byron Howard',),
 ('Joss Whedon',),
 ('David Yates',),
 ('Zack Snyder',),
 ('Bryan Singer',),
 ('Marc Forster',),
 ('Andrew Adamson',),
 ('Rob Marshall',),
 ('Barry Sonnenfeld',),
 ('Peter Jackson',),
 ('Marc Webb',),
 ('Ridley Scott',),
 ('Chris Weitz',),
 ('Anthony Russo',),
 ('Peter Berg',),
 ('Colin Trevorrow',),
 ('Shane Black',),
 ('Tim Burton',),
 ('Brett Ratner',),
 ('Dan Scanlon',),
 ('Michael Bay',),
 ('Joseph Kosinski',),
 ('John Lasseter',),
 ('Martin Campbell',),
 ('Lee Unkrich',),
 ('McG',),
 ('James Wan',),
 ('J.J. Abrams',),
 ('Baz Luhrmann',),
 ('Mike Newell',),
 ('Guillermo del Toro',),
 ('Steven Spielberg',),
 ('Peter Sohn',),
 ('Brenda Chapman',),
 ('Justin Lin',),
 ('Roland Emmerich',),
 ('Robert Zemeckis',),
 ('Lilly Wachowski',),
 ('Pete Docter',),
 ('Conrad Vernon',),
 ('Jon Favreau',),
 ('Martin Scorsese',),
 ('Rob Cohen',),
 ('David Ayer',),
 ('Tom Shadyac',),
 ('Doug Liman',),
 ('Kevin Reynolds',),
 ('Stephen Sommers',),
 ('Rupert Sanders',),
 ('Robert Stromberg',),
 ('Matt Reeves',),
 ('Roland Joffé',),
 ('Carl Rinsch',),
 ('Mike Mitchell',),
 ('Brad Bird',),
 ('Chris Williams',),
 ('Rich Moore',),
 ('Chris Sanders',),
 ('Jonathan Mostow',),
 ('James Gunn',),
 ('Hideaki Anno',),
 ('David Fincher',),
 ('Matthew Vaughn',),
 ('Francis Lawrence',),
 ('Jon Turteltaub',),
 ('Wolfgang Petersen',),
 ('James Bobin',),
 ('Chris Miller',),
 ('Duncan Jones',),
 ('Alan Taylor',),
 ('Michael Apted',),
 ('Oliver Stone',),
 ('Jan Pinkava',),
 ('Eric Darnell',),
 ('Shawn Levy',),
 ('Gavin Hood',),
 ('Chris Buck',),
 ('George Miller',),
 ('Ron Howard',),
 ('Kenneth Branagh',),
 ('Hoyt Yeatman',),
 ('Jonathan Liebesman',),
 ('Christopher McQuarrie',),
 ('Joe Johnston',),
 ('Steve Hickner',),
 ('Jennifer Yuh Nelson',),
 ('M. Night Shyamalan',),
 ('Simon Wells',),
 ('David Bowers',),
 ('Joe Wright',),
 ('Rob Minkoff',),
 ('Lee Tamahori',),
 ('Paul Feig',),
 ('Peter Ramsey',),
 ('Dean Parisot',),
 ('Edward Zwick',),
 ('Dean DeBlois',),
 ('Alex Proyas',),
 ('Richard Donner',),
 ('Ang Lee',),
 ('Jon M. Chu',),
 ('Breck Eisner',),
 ('Hironobu Sakaguchi',),
 ('Peter Weir',),
 ('Bill Condon',),
 ('Louis Leterrier',),
 ('Alejandro González Iñárritu',),
 ('David Soren',),
 ('Paul Greengrass',),
 ('Mark Osborne',),
 ('Peyton Reed',),
 ('Tim Johnson',),
 ('Phillip Noyce',),
 ('Darren Aronofsky',),
 ('Alfonso Cuarón',),
 ('Ralph Zondag',),
 ('Tom McGrath',),
 ('Chris Columbus',),
 ('Robert Schwentke',),
 ('Carlos Saldanha',),
 ('Guy Ritchie',),
 ('Paul Verhoeven',),
 ('John McTiernan',),
 ('Tony Gilroy',),
 ('Joel Schumacher',),
 ('John Woo',),
 ('Tim Story',),
 ('Mark Steven Johnson',),
 ('Neill Blomkamp',),
 ('David Twohy',),
 ('José Padilha',),
 ('James L. Brooks',),
 ('James Mangold',),
 ('George Lucas',),
 ('Thomas Langmann',),
 ('Cedric Nicolas-Troyan',),
 ('Roger Donaldson',),
 ('Dave Green',),
 ('Josh Trank',),
 ('Brad Peyton',),
 ('Roger Spottiswoode',),
 ('Steven Soderbergh',),
 ('Rob Letterman',),
 ('Michel Gondry',),
 ('Noam Murro',),
 ('Raja Gosnell',),
 ('Will Finn',),
 ('Jan de Bont',),
 ('Len Wiseman',),
 ('Frank Coraci',),
 ('Michael Mann',),
 ('Bo Welch',),
 ('Ron Clements',),
 ('Peter Chelsom',),
 ('Dominic Sena',),
 ('Tony Scott',),
 ('Paul Weitz',),
 ('Adam McKay',),
 ('Chuck Russell',),
 ('Quentin Tarantino',),
 ('Gary Trousdale',),
 ('Mark Dindal',),
 ('Simon West',),
 ('Stefen Fangmeier',),
 ('Spike Jonze',),
 ('Chris Wedge',),
 ('Florian Henckel von Donnersmarck',),
 ('Peter Hyams',),
 ('Tom Tykwer',),
 ('Pitof',),
 ('Brad Silberling',),
 ('Patrick Hughes',),
 ('Ericson Core',),
 ('Lawrence Guterman',),
 ('Ron Underwood',),
 ('Steve Martino',),
 ('David Mamet',),
 ('Zhang Yimou',),
 ('Ash Brannon',),
 ('Frank Oz',),
 ('Jay Roach',),
 ('Luc Besson',),
 ('Michael Patrick King',),
 ('Don Michael Paul',),
 ('Sergei Bodrov',),
 ('Wally Pfister',),
 ('Rupert Wyatt',),
 ('Mark Waters',),
 ('John Moore',),
 ('John Lee Hancock',),
 ('Renny Harlin',),
 ('Phil Lord',),
 ('Ben Stiller',),
 ('Tony Bancroft',),
 ('Timur Bekmambetov',),
 ('Walt Becker',),
 ('Dennis Dugan',),
 ('Sydney Pollack',),
 ('Thor Freudenthal',),
 ('Brian De Palma',),
 ('Mick Jackson',),
 ('Alan J. Pakula',),
 ('Kathryn Bigelow',),
 ('John Milius',),
 ('Andrei Konchalovsky',),
 ('Gary Ross',),
 ('Paul W.S. Anderson',),
 ('Genndy Tartakovsky',),
 ('Kevin Lima',),
 ('Daniel Espinosa',),
 ('Nancy Meyers',),
 ('Jill Culton',),
 ('Neil Burger',),
 ('Jean-Jacques Annaud',),
 ('Barry Cook',),
 ('Martin Brest',),
 ('Andrew Davis',),
 ('Bob Fosse',),
 ('Tarsem Singh',),
 ('Edgar Wright',),
 ('Jon Amiel',),
 ('Peter Segal',),
 ('Pete Travis',),
 ('George A. Romero',),
 ('Sylvester Stallone',),
 ('Todd Phillips',),
 ('Karey Kirkpatrick',),
 ('Gary Winick',),
 ('Mimi Leder',),
 ('Seth Gordon',),
 ('Adam Shankman',),
 ('D.J. Caruso',),
 ('Anthony Minghella',),
 ('Albert Hughes',),
 ('Les Mayfield',),
 ('Joe Pytka',),
 ('Scott Derrickson',),
 ('Ivan Reitman',),
 ('Eric Brevig',),
 ('Kelly Asbury',),
 ('Stephen Hopkins',),
 ('Jonathan Demme',),
 ('Henry Jaglom',),
 ('James Algar',),
 ('Vincent Ward',),
 ('Steven Brill',),
 ('Terry Gilliam',),
 ('Lucile Hadzihalilovic',),
 ('Roger Christian',),
 ('Joe Dante',),
 ('Kevin Costner',),
 ('Antony Hoffman',),
 ('Jacques Perrin',),
 ('Andrés Couturier',),
 ('Roger Allers',),
 ('Cody Cameron',),
 ('John Singleton',),
 ('Oliver Hirschbiegel',),
 ('Des McAnuff',),
 ('Chris Renaud',),
 ('Stephen Norrington',),
 ('Pierre Coffin',),
 ('David Kellogg',),
 ('Mike Nichols',),
 ('Vicky Jenson',),
 ('F. Gary Gray',),
 ('Antoine Fuqua',),
 ('Robert Luketic',),
 ('Gil Kenan',),
 ('Barry Levinson',),
 ('Jerry Zucker',),
 ('Andy Tennant',),
 ('Florent-Emilio Siri',),
 ('Gary Goldman',),
 ('Ron Shelton',),
 ('Àlex Pastor',),
 ('Henry Selick',),
 ('Kyle Balda',),
 ('Fergal Reilly',),
 ('Judd Apatow',),
 ('Steve Carr',),
 ('Mel Gibson',),
 ('David Silverman',),
 ('Frank Darabont',),
 ('Betty Thomas',),
 ('Garry Marshall',),
 ('Paul Tibbitt',),
 ('Clark Johnson',),
 ('Cameron Crowe',),
 ('Randall Wallace',),
 ('Jonathan Frakes',),
 ('George Clooney',),
 ('Gary Shore',),
 ('Andrzej Bartkowiak',),
 ('Måns Mårlind',),
 ('Gregory Hoblit',),
 ('Gary McKendry',),
 ('Wych Kaosayananda',),
 ('Mikael Salomon',),
 ('Bobby Farrelly',),
 ('Dan St. Pierre',),
 ('Kerry Conran',),
 ('Michael Caton-Jones',),
 ('Mikael Håfström',),
 ('Phil Alden Robinson',),
 ('David Slade',),
 ('Joseph Ruben',),
 ('Seth MacFarlane',),
 ('Alejandro Amenábar',),
 ('Kinka Usher',),
 ('Craig Gillespie',),
 ('Rob Bowman',),
 ('Doug Lefler',),
 ('Scott Waugh',),
 ('Lawrence Kasdan',),
 ('Michael Lembeck',),
 ('Tom Hooper',),
 ('Nora Ephron',),
 ('Angelina Jolie',),
 ('Clint Eastwood',),
 ('Larry Charles',),
 ('Stanley Kubrick',),
 ('Will Gluck',),
 ('Glenn Ficarra',),
 ('David S. Goyer',),
 ('Taylor Hackford',),
 ('Michael Lehmann',),
 ('Stuart Beattie',),
 ('Roman Polanski',),
 ('Robert Rodriguez',),
 ('Baltasar Kormákur',),
 ('Daniel Lee',),
 ('Keenen Ivory Wayans',),
 ('Rob Reiner',),
 ('Marco Schnabel',),
 ('Demian Lichtenstein',),
 ('Josh Gordon',),
 ('Tim Hill',),
 ('David Frankel',),
 ('Marc Lawrence',),
 ('Peter Billingsley',),
 ('Wes Ball',),
 ('Ryan Murphy',),
 ('Robert Redford',),
 ('Jay Russell',),
 ('Kenny Ortega',),
 ('David McNally',),
 ('Brian Robbins',),
 ('Brian Levant',),
 ('Steven Zaillian',),
 ('Sam Fell',),
 ('Jon Avnet',),
 ('Robert Stevenhagen',),
 ('Kevin Donovan',),
 ('Geoff Murphy',),
 ('David O. Russell',),
 ('Babak Najafi',),
 ('Jean-Pierre Jeunet',),
 ('Anthony Stacchi',),
 ('Griffin Dunne',),
 ('John Pasquin',),
 ('Ruben Fleischer',),
 ('Harold Ramis',),
 ('Kevin Macdonald',),
 ('Donald Petrie',),
 ('Jorge Blanco',),
 ('Stuart Baird',),
 ('Joel Coen',),
 ('Robert Lorenz',),
 ('Harold Becker',),
 ('Scott Stewart',),
 ('Tony Bill',),
 ('Rod Lurie',),
 ('Walter Hill',),
 ('Akiva Goldsman',),
 ('Harald Zwart',),
 ('Walter Salles',),
 ('Iain Softley',),
 ('Frank Miller',),
 ('David Koepp',),
 ('Uwe Boll',),
 ('Soi Cheang',),
 ('John Dahl',),
 ('Tim Miller',),
 ('Stephen Herek',),
 ('Peter MacDonald',),
 ('Anthony Hemingway',),
 ('Sean Anders',),
 ('Brian Taylor',),
 ('John Madden',),
 ('Kevin Bray',),
 ('Mike Gabriel',),
 ('Sam Weisman',),
 ('Jesse Dylan',),
 ('Wayne Wang',),
 ('Gabriele Muccino',),
 ('Tom Dey',),
 ('Jimmy Hayward',),
 ('Alan Parker',),
 ('John Frankenheimer',),
 ('Paul King',),
 ('Akiva Schaffer',),
 ('William Friedkin',),
 ('Kent Alterman',),
 ('Peter Lord',),
 ('Shekhar Kapur',),
 ('Karyn Kusama',),
 ('Ronald F. Maxwell',),
 ('Robert Butler',),
 ('Steve Antin',),
 ('Jim Gillespie',),
 ('Francis Ford Coppola',),
 ('Richard Lester',),
 ('Scott Cooper',),
 ('Curtis Hanson',),
 ('Phyllida Lloyd',),
 ('Jay Chandrasekhar',),
 ('Terrence Malick',),
 ('David Dobkin',),
 ('Miloš Forman',),
 ('Pierre Morel',),
 ('Paul Hunter',),
 ('Steve Oedekerk',),
 ('John Whitesell',),
 ('George Nolfi',),
 ('Neil Jordan',),
 ('Rawson Marshall Thurber',),
 ('Spike Lee',),
 ('Brian Helgeland',),
 ('Frank Marshall',),
 ('Hideo Nakata',),
 ('Peter Hewitt',),
 ('Joe Roth',),
 ('Bennett Miller',),
 ('Jaume Collet-Serra',),
 ('Andy Fickman',),
 ('James McTeigue',),
 ("Matthew O'Callaghan",),
 ('Angela Robinson',),
 ('Gary Fleder',),
 ('Tommy Wirkola',),
 ('Adrian Lyne',),
 ('Stephen Gaghan',),
 ('Jorge R. Gutierrez',),
 ('Richard Loncraine',),
 ('Christophe Gans',),
 ('Howard Deutch',),
 ('Jon Hurwitz',),
 ('Steven Quale',),
 ('John Landis',),
 ('Alexander Witt',),
 ('Beeban Kidron',),
 ('Carl Franklin',),
 ('Steven Seagal',),
 ('Danny Boyle',),
 ('Andrew Bergman',),
 ('Barbet Schroeder',),
 ('Peter Webber',),
 ('Andrew Niccol',),
 ('John Carpenter',),
 ('Wes Anderson',),
 ('David Cronenberg',),
 ('John Stockwell',),
 ('David Gordon Green',),
 ('Jim Sheridan',),
 ('Costa-Gavras',),
 ('Patrick Read Johnson',),
 ('Richard LaGravenese',),
 ('Danny DeVito',),
 ('George Armitage',),
 ('Patrick Lussier',),
 ('James Wong',),
 ('Richard Curtis',),
 ('Chuck Bowman',),
 ('Olivier Megaton',),
 ('Deepa Mehta',),
 ('Warren Beatty',),
 ('Penny Marshall',),
 ('Ted Kotcheff',),
 ('Andrei Tarkovsky',),
 ('Yvette Kaplan',),
 ('Stephen Frears',),
 ('P.J. Hogan',),
 ('Brad Furman',),
 ('Terence Young',),
 ('David Zucker',),
 ('Denis Villeneuve',),
 ('Thomas Carter',),
 ('Roger Michell',),
 ('Luis Llosa',),
 ('Melville Shavelson',),
 ('Garth Jennings',),
 ('Joel Zwick',),
 ('Russell Mulcahy',),
 ('David R. Ellis',),
 ('Peter Howitt',),
 ('John A. Davis',),
 ('David Lynch',),
 ('Julie Taymor',),
 ('Mathieu Kassovitz',),
 ('John Gray',),
 ('John Schultz',),
 ('Sean Penn',),
 ('Susan Stroman',),
 ('Simon Wincer',),
 ('Billy Bob Thornton',),
 ('Danny Pang',),
 ('George P. Cosmatos',),
 ('Oliver Parker',),
 ('Lawrence Kasanoff',),
 ('Ben Affleck',),
 ('Brian Gibson',),
 ('Ben Sharpsteen',),
 ('Michael Cimino',),
 ('Paul McGuigan',),
 ('Gus Van Sant',),
 ('Roger Kumble',),
 ('Burr Steers',),
 ('Nick Park',),
 ('John Hamburg',),
 ('Reginald Hudlin',),
 ('Joseph L. Mankiewicz',),
 ('Barbra Streisand',),
 ('Mark Pellington',),
 ('John Glen',),
 ('Catherine Hardwicke',),
 ('John Herzfeld',),
 ('Annabel Jankel',),
 ('Julie Anne Robinson',),
 ('Seth Rogen',),
 ('Sngmoo Lee',),
 ('Jamel Debbouze',),
 ('Gordon Chan',),
 ('Asger Leth',),
 ('John G. Avildsen',),
 ('Anne Fletcher',),
 ('Bruce Beresford',),
 ('Sam Taylor-Johnson',),
 ('Ken Kwapis',),
 ('Wes Craven',),
 ('Etan Cohen',),
 ('Nick Cassavetes',),
 ('Nicholas Stoller',),
 ('Mark A.Z. Dippé',),
 ('Callan Brunker',),
 ('Nimród Antal',),
 ('Alejandro Agresti',),
 ('Peter Hedges',),
 ('Paul Weiland',),
 ('Colin Strause',),
 ('Joan Chen',),
 ('Greg Mottola',),
 ('Jake Kasdan',),
 ('Diane Keaton',),
 ('Kelly Makin',),
 ('Stephen Daldry',),
 ('Christian Duguay',),
 ('Justin Chadwick',),
 ("Pat O'Connor",),
 ('Frederik Du Chau',),
 ('Irwin Winkler',),
 ('Joseph Kahn',),
 ('Sofia Coppola',),
 ('Stephen T. Kay',),
 ('Juan Antonio Bayona',),
 ('Elaine May',),
 ('Dennie Gordon',),
 ('Charles Shyer',),
 ('Ulu Grosbard',),
 ('William Malone',),
 ('Malcolm D. Lee',),
 ('Jerry Jameson',),
 ('Mic Rodgers',),
 ('Christian Alvart',),
 ('Jean-Marie Poiré',),
 ('Marc F. Adler',),
 ('Geoffrey Sax',),
 ('Richard Shepard',),
 ('Peter Chan',),
 ('Sergei Bodrov Jr.',),
 ('Bong Joon-ho',),
 ('Bibo Bergeron',),
 ('Jeff Nathanson',),
 ('S.S. Rajamouli',),
 ('Charles S. Dutton',),
 ('Jonathan Lynn',),
 ('David Carson',),
 ('Wong Kar-wai',),
 ('Yuefeng Song',),
 ('Norman Jewison',),
 ('David Mirkin',),
 ('Luis Mandoki',),
 ('Lee Daniels',),
 ('Jeb Stuart',),
 ('Steve Miner',),
 ('Paul Thomas Anderson',),
 ('David Leland',),
 ('J Blakeson',),
 ('Ryan Coogler',),
 ('Kirk Jones',),
 ('Jennifer Flackett',),
 ('Kevin Smith',),
 ('Christian Ditter',),
 ('Charles Martin Smith',),
 ('Fyodor Bondarchuk',),
 ('Irvin Kershner',),
 ('Steve Pink',),
 ('Scott Hicks',),
 ('Kirk De Micco',),
 ('Chris Rock',),
 ('Wilson Yip',),
 ('Robert Wise',),
 ('Kevin Rodney Sullivan',),
 ('Kevin Munroe',),
 ('Mike Tollin',),
 ('Patrick Tatopoulos',),
 ('Gary David Goldberg',),
 ('Tobe Hooper',),
 ('Alan Poul',),
 ('Luke Greenfield',),
 ('Gil Junger',),
 ('Michael Ritchie',),
 ('Steven E. de Souza',),
 ('Alexandre Aja',),
 ('Michael Rymer',),
 ('Hugh Wilson',),
 ('Mike Hodges',),
 ('Scott Mann',),
 ('Susanna White',),
 ('Chris Carter',),
 ("Tommy O'Haver",),
 ('Peter Landesman',),
 ('Gary Chapman',),
 ('Craig Mazin',),
 ('Allen Hughes',),
 ('Kimble Rendall',),
 ('Peter Yates',),
 ('Lasse Hallström',),
 ('Jean-Marc Vallée',),
 ('Tsui Hark',),
 ('Lexi Alexander',),
 ('Ronny Yu',),
 ('Bille August',),
 ('Moustapha Akkad',),
 ('Jean-Paul Rappeneau',),
 ('Joachim Rønning',),
 ('Tony Kaye',),
 ('Ken Scott',),
 ('Hugh Johnson',),
 ('Hayao Miyazaki',),
 ('George Tillman, Jr.',),
 ('Rand Ravich',),
 ('Hugh Hudson',),
 ('Ben Stassen',),
 ('Chris Gorak',),
 ('Scott Speer',),
 ('Joe Charbanic',),
 ('Jonathan Hensleigh',),
 ('Danny Cannon',),
 ('Boaz Yakin',),
 ('Richard Marquand',),
 ('Neil Marshall',),
 ('David Wain',),
 ('Jared Hess',),
 ('Rupert Wainwright',),
 ('John Luessenhop',),
 ('Justin Zackham',),
 ('John Gatins',),
 ('Miguel Sapochnik',),
 ('Shim Hyung-Rae',),
 ('Don Scardino',),
 ('Tim Robbins',),
 ('Tom Reeve',),
 ('Nanette Burstein',),
 ('Ariel Vromen',),
 ('Lewis Gilbert',),
 ('John Francis Daley',),
 ('J.B. Rogers',),
 ('Michael Sucsy',),
 ('Tom Vaughan',),
 ('Stephen Hillenburg',),
 ('Stig Bergqvist',),
 ('Jason Reitman',),
 ('Alexander Payne',),
 ('Jonathan Levine',),
 ('Rian Johnson',),
 ('Chris Noonan',),
 ('Michael McCullers',),
 ('Forest Whitaker',),
 ('Woody Allen',),
 ('Peter Lepeniotis',),
 ('Ted Demme',),
 ('William Shatner',),
 ('James Gartner',),
 ('Lee Toland Krieger',),
 ('Tim McCanlies',),
 ('Drew Goddard',),
 ('Jason Friedberg',),
 ('Paul Michael Glaser',),
 ('John R. Leonetti',),
 ('Tom Hanks',),
 ('Kimberly Peirce',),
 ('Liz Friedlander',),
 ('Phil Joanou',),
 ('Shane Acker',),
 ('Martha Coolidge',),
 ('Stephen Anderson',),
 ('Troy Miller',),
 ('Tate Taylor',),
 ('Brett Leonard',),
 ('Alister Grierson',),
 ('Nick Hurran',),
 ('Charles Stone III',),
 ('Paul Haggis',),
 ('Kurt Wimmer',),
 ('Jean-François Richet',),
 ('Kevin Hooks',),
 ('Ellory Elkayem',),
 ('Niki Caro',),
 ('Vincenzo Natali',),
 ('Willard Huyck',),
 ("Gavin O'Connor",),
 ('Bruce Hunt',),
 ('Christopher Roberts',),
 ('Kim Jee-woon',),
 ('Nick Hamm',),
 ('Andy Cadiff',),
 ('Mike Disa',),
 ('Richard J. Lewis',),
 ('Sergio Leone',),
 ('Niels Arden Oplev',),
 ('Michael Radford',),
 ('Steve Boyum',),
 ('Chen Kaige',),
 ('Corey Yuen Kwai',),
 ('Andrew Dominik',),
 ('Jackie Chan',),
 ('Laurent Tirard',),
 ('Reinhard Klooss',),
 ('Frédéric Auburtin',),
 ('Olivier Dahan',),
 ('Maksim Fadeev',),
 ('Liliana Cavani',),
 ('Elizabeth Banks',),
 ('Edward Norton',),
 ('Ben Falcone',),
 ('Richard Attenborough',),
 ('Don Mancini',),
 ('John Maybury',),
 ('Norton Virgien',),
 ('Shinji Aramaki',),
 ('Miguel Arteta',),
 ('James Gray',),
 ('Janusz Kamiński',),
 ('Robert B. Weide',),
 ('Jeff Wadlow',),
 ('Agustín Díaz Yanes',),
 ('Camille Delamarre',),
 ('David Lean',),
 ('Richard Eyre',),
 ('Nicholas Meyer',),
 ('Callie Khouri',),
 ('Sanaa Hamri',),
 ('Todd Graff',),
 ('Philip Kaufman',),
 ('Saul Dibb',),
 ('Walter Murch',),
 ('Richard Linklater',),
 ('E. Elias Merhige',),
 ('Menno Meyjes',),
 ('Jodie Foster',),
 ('Scott Frank',),
 ('Kevin Allen',),
 ('Michael Cristofer',),
 ('Andrew Morahan',),
 ('Bob Rafelson',),
 ('Michael Cohn',),
 ('Alan Shapiro',),
 ('Fernando Meirelles',),
 ('Michael Hoffman',),
 ('Oleg Stepchenko',),
 ('Michael Winterbottom',),
 ('Michael Pressman',),
 ('Sharon Maguire',),
 ('Charles Herman-Wurmfeld',),
 ('Gábor Csupó',),
 ('Tyler Perry',),
 ('Joe Carnahan',),
 ('John Polson',),
 ('Bernardo Bertolucci',),
 ('Cathy Malkasian',),
 ('Chris Nahon',),
 ('Fred Wolf',),
 ('Bille Woodruff',),
 ('Victor Salva',),
 ('Mark Helfrich',),
 ('Steve Bendelack',),
 ('Dwight H. Little',),
 ('Guillaume Canet',),
 ('Kirsten Sheridan',),
 ('Richard Fleischer',),
 ('Bob Spiers',),
 ('Damien Dante Wayans',),
 ('John Wells',),
 ('Tim Fywell',),
 ('Nigel Cole',),
 ('Dexter Fletcher',),
 ('Jeremy Leven',),
 ('Sylvain White',),
 ('Troy Nixey',),
 ('Philip G. Atwell',),
 ('Jeff Schaffer',),
 ('James Bridges',),
 ('Steve Barron',),
 ('Bill Paxton',),
 ('Richard Kelly',),
 ('Carter Smith',),
 ('John Schlesinger',),
 ('Ringo Lam',),
 ('Bruce McCulloch',),
 ('Patricia Riggen',),
 ('Pascal Chaumeil',),
 ('Jonathan Kaplan',),
 ('Ole Bornedal',),
 ('Richard Benjamin',),
 ('Craig R. Baxley',),
 ('John Hillcoat',),
 ('John Guillermin',),
 ('Marcos Siega',),
 ('Rachel Talalay',),
 ('Jeffrey W. Byrd',),
 ('Atom Egoyan',),
 ('Robert Towne',),
 ('Giuseppe Tornatore',),
 ('Werner Herzog',),
 ('Jérôme Deschamps',),
 ('Inna Evlannikova',),
 ('Jonathan English',),
 ('Sergey Bondarchuk',),
 ('Teddy Chan',),
 ('Mario Van Peebles',),
 ('Leonard Nimoy',),
 ('Herbert Ross',),
 ('Bonnie Hunt',),
 ('Neil LaBute',),
 ('Grant Heslov',),
 ('George Gallo',),
 ('Sidney Lumet',),
 ('Douglas McGrath',),
 ('Kevin Spacey',),
 ('Richard Williams',),
 ('Mary McGuckian',),
 ('Tony Goldwyn',),
 ('Jonathan Newman',),
 ('Michael Dinner',),
 ('Joseph Sargent',),
 ('Jerry Zaks',),
 ('Fred Durst',),
 ('Anne Fontaine',),
 ('Jon Cassar',),
 ('Mira Nair',),
 ('Mel Brooks',),
 ('Russell Crowe',),
 ('Jessie Nelson',),
 ('Christopher Spencer',),
 ('Mike Bigelow',),
 ('Daniel Sackheim',),
 ('Deborah Kaplan',),
 ('Uli Edel',),
 ('Fred Dekker',),
 ('Brian Trenchard-Smith',),
 ('Blake Edwards',),
 ('Laurence Dunmore',),
 ('Christian Carion',),
 ('Dax Shepard',),
 ('Rowan Joffe',),
 ('John Curran',),
 ('Juan José Campanella',),
 ('Trey Parker',),
 ('Stuart Gillard',),
 ('Katt Shea',),
 ('Joshua Michael Stern',),
 ('Tomas Alfredson',),
 ('John Duigan',),
 ('Colin Higgins',),
 ('Jim Sonzero',),
 ('Penelope Spheeris',),
 ('Jeff Tremaine',),
 ('Jeannot Szwarc',),
 ('Steve McQueen',),
 ('Thea Sharrock',),
 ('Jon Lucas',),
 ('Robin Budd',),
 ('Ava DuVernay',),
 ('Steve Trenbirth',),
 ('Mennan Yapo',),
 ('Jun Falkenstein',),
 ('Tom McCarthy',),
 ('Takashi Shimizu',),
 ('Gary Nelson',),
 ('Anton Corbijn',),
 ('Gregory Nava',),
 ('John Patrick Shanley',),
 ('Joshua Logan',),
 ('Steve Beck',),
 ('Todd Strauss-Schulson',),
 ('John McNaughton',),
 ('Nelson McCormick',),
 ('Eric Valette',),
 ('Andrew Fleming',),
 ('Michael Spierig',),
 ('Jim Field Smith',),
 ('Thomas Bezucha',),
 ('William Brent Bell',),
 ('Ben Gluck',),
 ('Jessica Bendinger',),
 ('Henry Joost',),
 ('Ed Harris',),
 ('Alfred Hitchcock',),
 ('Shana Feste',),
 ('Steve Rash',),
 ('Mike Binder',),
 ('Michael J. Bassett',),
 ('Frank Nissen',),
 ('Stephen Chow',),
 ('Peter Hastings',),
 ('Paul Abascal',),
 ('Chris Koch',),
 ('Amy Heckerling',),
 ('Michael Moore',),
 ('George Stevens',),
 ('Billy Ray',),
 ('Mark Mylod',),
 ('Stephen St. Leger',),
 ('Michael O. Sajbel',),
 ('Charles T. Kanganis',),
 ('Damon Santostefano',),
 ('Bob Clark',),
 ('Frank Passingham',),
 ('Benson Lee',),
 ('Glen Morgan',),

In [37]:
cur.execute('SELECT title,revenue FROM movies ORDER BY revenue desc LIMIT 10')
cur.fetchall()

[('Avatar', 2787965087),
 ('Titanic', 1845034188),
 ('The Avengers', 1519557910),
 ('Jurassic World', 1513528810),
 ('Furious 7', 1506249360),
 ('Avengers: Age of Ultron', 1405403694),
 ('Frozen', 1274219009),
 ('Iron Man 3', 1215439994),
 ('Minions', 1156730962),
 ('Captain America: Civil War', 1153304495)]

In [38]:
cur.execute('SELECT movies.*, directors.* FROM movies INNER JOIN directors ON movies.director_id = directors.id ORDER BY movies.budget DESC LIMIT 10')
cur.fetchall()

[(43614,
  'Pirates of the Caribbean: On Stranger Tides',
  380000000,
  135,
  '2011-05-14',
  1045713802,
  'Pirates of the Caribbean: On Stranger Tides',
  6.4,
  4948,
  "Captain Jack Sparrow crosses paths with a woman from his past, and he's not sure if it's love -- or if she's a ruthless con artist who's using him to find the fabled Fountain of Youth. When she forces him aboard the Queen Anne's Revenge, the ship of the formidable pirate Blackbeard, Jack finds himself on an unexpected adventure in which he doesn't know who to fear more: Blackbeard or the woman from his past.",
  'Live Forever Or Die Trying.',
  1865,
  4775,
  'Rob Marshall',
  4775,
  2,
  17633,
  'Directing'),
 (43598,
  "Pirates of the Caribbean: At World's End",
  300000000,
  139,
  '2007-05-19',
  961000000,
  "Pirates of the Caribbean: At World's End",
  6.9,
  4500,
  'Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.',
  'At the end of the world, the adventure begins.',
  285,
  4763,
  'Gore Verbinski',
  4763,
  2,
  1704,
  'Directing'),
 (43604,
  'Avengers: Age of Ultron',
  280000000,
  134,
  '2015-04-22',
  1405403694,
  'Avengers: Age of Ultron',
  7.3,
  6767,
  'When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.',
  'A New Age Has Come.',
  99861,
  4769,
  'Joss Whedon',
  4769,
  2,
  12891,
  'Directing'),
 (43607,
  'Superman Returns',
  270000000,
  57,
  '2006-06-28',
  391081192,
  'Superman Returns',
  5.4,
  1400,
  'Superman returns to discover his 5-year absence has allowed Lex Luthor to walk free, and that those he was closest too felt abandoned and have moved on. Luthor plots his ultimate revenge that could see millions killed and change the face of the planet forever, as well as ridding himself of the Man of Steel.',
  None,
  1452,
  4772,
  'Bryan Singer',
  4772,
  2,
  9032,
  'Directing'),
 (43601,
  'John Carter',
  260000000,
  43,
  '2012-03-07',
  284139100,
  'John Carter',
  6.1,
  2124,
  "John Carter is a war-weary, former military captain who's inexplicably transported to the mysterious and exotic planet of Barsoom (Mars) and reluctantly becomes embroiled in an epic conflict. It's a world on the brink of collapse, and Carter rediscovers his humanity when he realizes the survival of Barsoom and its people rests in his hands.",
  'Lost in our world, found in another.',
  49529,
  4766,
  'Andrew Stanton',
  4766,
  2,
  7,
  'Directing'),
 (43603,
  'Tangled',
  260000000,
  48,
  '2010-11-24',
  591794936,
  'Tangled',
  7.4,
  3330,
  "When the kingdom's most wanted-and most charming-bandit Flynn Rider hides out in a mysterious tower, he's taken hostage by Rapunzel, a beautiful and feisty tower-bound teen with 70 feet of magical, golden hair. Flynn's curious captor, who's looking for her ticket out of the tower where she's been locked away for years, strikes a deal with the handsome thief and the unlikely duo sets off on an action-packed escapade, complete with a super-cop horse, an over-protective chameleon and a gruff gang of pub thugs.",
  "They're taking adventure to new lengths.",
  38757,
  4768,
  'Byron Howard',
  4768,
  2,
  76595,
  'Directing'),
 (43602,
  'Spider-Man 3',
  258000000,
  115,
  '2007-05-01',
  890871626,
  'Spider-Man 3',
  5.9,
  3576,
  'The seemingly invincible Spider-Man goes up against an all-new crop of villain – including the shape-shifting Sandman. While Spider-Man’s superpowers are altered by an alien organism, his alter ego, Peter Parker, deals with nemesis Eddie Brock and also gets caught up in a love triangle.',
  'The battle within.',
  559,
  4767,
  'Sam Raimi',
  4767,
  2,
  7623,
  'Directing'),
 (43610,
  'The Lone Ranger',
  255000000,
  49,
  '2013-07-03',
  89289910,
  'The Lone Ranger',
  5.9,
  2311,
  'The Texas Rangers chase down a gang of outlaws led by Butch Cavendish, but the gang ambushes the Rangers, seemingly killing them all. One survivor is found, however, by an American Indian named Tonto, who nurses him back to health. The Ranger, donning a mask and riding a white stallion named Silver, teams up with Tonto to bring the unscrupulous gang and others of that ilk to justice.',
  'Never Take Off the Mask',
  57201,
  4763,
  'Gore Verbinski',
  4763,
  2,
  1704,
  'Directing'),
 (43600,
  'The Dark Knight Rises',
  250000000,
  112,
  '2012-07-16',
  1084939099,
  'The Dark Knight Rises',
  7.6,
  9106,
  "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
  'The Legend Ends',
  49026,
  4765,
  'Christopher Nolan',
  4765,
  2,
  525,
  'Directing'),
 (43605,
  'Harry Potter and the Half-Blood Prince',
  250000000,
  98,
  '2009-07-07',
  933959197,
  'Harry Potter and the Half-Blood Prince',
  7.4,
  5293,
  "As Harry begins his sixth year at Hogwarts, he discovers an old book marked as 'Property of the Half-Blood Prince', and begins to learn more about Lord Voldemort's dark past.",
  'Dark Secrets Revealed',
  767,
  4770,
  'David Yates',
  4770,
  2,
  11343,
  'Directing')]

In [39]:
cur.execute('SELECT name FROM directors WHERE id = (SELECT director_id FROM movies GROUP BY director_id ORDER BY COUNT(*) DESC LIMIT 1)')
cur.fetchall()

[('Steven Spielberg',)]

In [40]:
cur.execute('SELECT name FROM directors WHERE id = (SELECT director_id FROM movies GROUP BY director_id ORDER BY COUNT(*) DESC LIMIT 1)')
cur.fetchall()

[('Steven Spielberg',)]

In [41]:
movies[movies['original_title'] == 'The Cat in the Hat']

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
265,43862,The Cat in the Hat,0,18,2003-11-21,0,The Cat in the Hat,4.9,366,Conrad and Sally Walden are home alone with th...,Don't mess with the hat.,10588,4919

In [44]:
a = list(directors.columns)
a.extend(list(movies.columns))
a

['name',
 'id',
 'gender',
 'uid',
 'department',
 'id',
 'original_title',
 'budget',
 'popularity',
 'release_date',
 'revenue',
 'title',
 'vote_average',
 'vote_count',
 'overview',
 'tagline',
 'uid',
 'director_id']

In [46]:
##### all the possible details of top 10 movies with highest budget
cur.execute('select * from directors join movies on directors.id = movies.director_id order by budget desc limit 10 ')
pd.DataFrame(cur.fetchall(),columns = a )

,name,id,gender,uid,department,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
0,Rob Marshall,4775,2,17633,Directing,43614,Pirates of the Caribbean: On Stranger Tides,380000000,135,2011-05-14,1045713802,Pirates of the Caribbean: On Stranger Tides,6.4,4948,Captain Jack Sparrow crosses paths with a woma...,Live Forever Or Die Trying.,1865,4775
1,Gore Verbinski,4763,2,1704,Directing,43598,Pirates of the Caribbean: At World's End,300000000,139,2007-05-19,961000000,Pirates of the Caribbean: At World's End,6.9,4500,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",285,4763
2,Joss Whedon,4769,2,12891,Directing,43604,Avengers: Age of Ultron,280000000,134,2015-04-22,1405403694,Avengers: Age of Ultron,7.3,6767,When Tony Stark tries to jumpstart a dormant p...,A New Age Has Come.,99861,4769
3,Bryan Singer,4772,2,9032,Directing,43607,Superman Returns,270000000,57,2006-06-28,391081192,Superman Returns,5.4,1400,Superman returns to discover his 5-year absenc...,None,1452,4772
4,Andrew Stanton,4766,2,7,Directing,43601,John Carter,260000000,43,2012-03-07,284139100,John Carter,6.1,2124,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",49529,4766
5,Byron Howard,4768,2,76595,Directing,43603,Tangled,260000000,48,2010-11-24,591794936,Tangled,7.4,3330,When the kingdom's most wanted-and most charmi...,They're taking adventure to new lengths.,38757,4768
6,Sam Raimi,4767,2,7623,Directing,43602,Spider-Man 3,258000000,115,2007-05-01,890871626,Spider-Man 3,5.9,3576,The seemingly invincible Spider-Man goes up ag...,The battle within.,559,4767
7,Gore Verbinski,4763,2,1704,Directing,43610,The Lone Ranger,255000000,49,2013-07-03,89289910,The Lone Ranger,5.9,2311,The Texas Rangers chase down a gang of outlaws...,Never Take Off the Mask,57201,4763
8,Christopher Nolan,4765,2,525,Directing,43600,The Dark Knight Rises,250000000,112,2012-07-16,1084939099,The Dark Knight Rises,7.6,9106,Following the death of District Attorney Harve...,The Legend Ends,49026,4765
9,David Yates,4770,2,11343,Directing,43605,Harry Potter and the Half-Blood Prince,250000000,98,2009-07-07,933959197,Harry Potter and the Half-Blood Prince,7.4,5293,"As Harry begins his sixth year at Hogwarts, he...",Dark Secrets Revealed,767,4770

In [45]:
##### details+ of top 10 revenue making movies
cur.execute('select * from directors join movies on directors.id = movies.director_id order by revenue desc limit 10 ')
pd.DataFrame(cur.fetchall(),columns = a )

,name,id,gender,uid,department,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
0,James Cameron,4762,2,2710,Directing,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762
1,James Cameron,4762,2,2710,Directing,43622,Titanic,200000000,100,1997-11-18,1845034188,Titanic,7.5,7562,"84 years later, a 101-year-old woman named Ros...",Nothing on Earth could come between them.,597,4762
2,Joss Whedon,4769,2,12891,Directing,43613,The Avengers,220000000,144,2012-04-25,1519557910,The Avengers,7.4,11776,When an unexpected enemy emerges and threatens...,Some assembly required.,24428,4769
3,Colin Trevorrow,4783,2,930707,Directing,43625,Jurassic World,150000000,418,2015-06-09,1513528810,Jurassic World,6.5,8662,Twenty-two years after the events of Jurassic ...,The park is open.,135397,4783
4,James Wan,4794,2,2127,Directing,43641,Furious 7,190000000,102,2015-04-01,1506249360,Furious 7,7.3,4176,Deckard Shaw seeks revenge against Dominic Tor...,Vengeance Hits Home,168259,4794
5,Joss Whedon,4769,2,12891,Directing,43604,Avengers: Age of Ultron,280000000,134,2015-04-22,1405403694,Avengers: Age of Ultron,7.3,6767,When Tony Stark tries to jumpstart a dormant p...,A New Age Has Come.,99861,4769
6,Chris Buck,4844,0,15774,Directing,43721,Frozen,150000000,165,2013-11-27,1274219009,Frozen,7.3,5295,Young princess Anna of Arendelle dreams about ...,Only the act of true love will thaw a frozen h...,109445,4844
7,Shane Black,4784,2,1108,Directing,43628,Iron Man 3,200000000,77,2013-04-18,1215439994,Iron Man 3,6.8,8806,When Tony Stark's world is torn apart by a for...,Unleash the power behind the armor.,68721,4784
8,Kyle Balda,5045,0,8023,Directing,44143,Minions,74000000,875,2015-06-17,1156730962,Minions,6.4,4571,"Minions Stuart, Kevin and Bob are recruited by...","Before Gru, they had a history of bad bosses",211672,5045
9,Anthony Russo,4781,2,19271,Directing,43623,Captain America: Civil War,250000000,198,2016-04-27,1153304495,Captain America: Civil War,7.1,7241,"Following the events of Age of Ultron, the col...",Divided We Fall,271110,4781

In [47]:
cur.execute('SELECT name,count(original_title),sum(revenue) from directors join movies on directors.id=movies.director_id group by director_id')
pd.DataFrame(cur.fetchall(),columns = ['director','total_mvies','total_revenue'])

               director  total_mvies  total_revenue
0         James Cameron            7     5883569439
1        Gore Verbinski            7     3177013357
2            Sam Mendes            7     2713548809
3     Christopher Nolan            8     4227483234
4        Andrew Stanton            4     2109045355
...                 ...          ...            ...
2344      Shane Carruth            1         424760
2345   Neill Dela Llana            1              0
2346        Scott Smith            1              0
2347        Daniel Hsia            1              0
2348   Brian Herzlinger            1              0

[2349 rows x 3 columns]